~/Scripts/modernizr/modernizr-2.8.3.min.js
~/Scripts/jquery/jquery-3.6.0.min.js
~/Scripts/moment/moment.min.js
~/Scripts/popper/umd/popper.min.js
~/Scripts/linq/linq.min.js
~/Scripts/bootstrap/bootstrap.min.js
~/Scripts/bootstrap/bootstrap-validator/bootstrap-validator.min.js
~/Scripts/bootstrap/bootstrap-datetimepicker/bootstrap-datetimepicker.js
~/Scripts/material/material.min.js
~/Scripts/datatable/jquery.dataTables.min.js
~/Scripts/datatable/dataTables.material.min.js
~/Scripts/datatable/dataTables.rowReorder.min.js
~/Scripts/datatable/dataTables.responsive.min.js
~/Scripts/datatable/fnFilterClear.min.js
~/Scripts/trumbowyg/trumbowyg.min.js
~/Scripts/trumbowyg/trumbowyg.table.min.js
~/Scripts/trumbowyg/trumbowyg.colors.min.js
~/Scripts/trumbowyg/es.min.js
~/Scripts/views/common/common.js