// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace PepinoHealth.App.Controllers
{
    public partial class HomeController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HomeController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected HomeController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LogOut()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LogOut);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ValidateUser()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ValidateUser);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GrantAccess()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GrantAccess);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HomeController Actions { get { return MVC.Home; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Home";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Home";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Login = "Login";
            public readonly string QuickLinksV2 = "QuickLinksV2";
            public readonly string RegistrationV2 = "RegistrationV2";
            public readonly string RevisitRegistration = "RevisitRegistration";
            public readonly string LogOut = "LogOut";
            public readonly string Index = "Index";
            public readonly string DashBoard = "DashBoard";
            public readonly string QuickLinks = "QuickLinks";
            public readonly string Registration = "Registration";
            public readonly string Page1 = "Page1";
            public readonly string Page2 = "Page2";
            public readonly string Datatable = "Datatable";
            public readonly string AdvanceReceipt = "AdvanceReceipt";
            public readonly string ValidateUser = "ValidateUser";
            public readonly string GrantAccess = "GrantAccess";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Login = "Login";
            public const string QuickLinksV2 = "QuickLinksV2";
            public const string RegistrationV2 = "RegistrationV2";
            public const string RevisitRegistration = "RevisitRegistration";
            public const string LogOut = "LogOut";
            public const string Index = "Index";
            public const string DashBoard = "DashBoard";
            public const string QuickLinks = "QuickLinks";
            public const string Registration = "Registration";
            public const string Page1 = "Page1";
            public const string Page2 = "Page2";
            public const string Datatable = "Datatable";
            public const string AdvanceReceipt = "AdvanceReceipt";
            public const string ValidateUser = "ValidateUser";
            public const string GrantAccess = "GrantAccess";
        }


        static readonly ActionParamsClass_LogOut s_params_LogOut = new ActionParamsClass_LogOut();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LogOut LogOutParams { get { return s_params_LogOut; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LogOut
        {
            public readonly string returnUrl = "returnUrl";
        }
        static readonly ActionParamsClass_ValidateUser s_params_ValidateUser = new ActionParamsClass_ValidateUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ValidateUser ValidateUserParams { get { return s_params_ValidateUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ValidateUser
        {
            public readonly string profile = "profile";
        }
        static readonly ActionParamsClass_GrantAccess s_params_GrantAccess = new ActionParamsClass_GrantAccess();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GrantAccess GrantAccessParams { get { return s_params_GrantAccess; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GrantAccess
        {
            public readonly string profile = "profile";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string DashBoard = "DashBoard";
                public readonly string Datatable = "Datatable";
                public readonly string Index = "Index";
                public readonly string Login = "Login";
                public readonly string Page1 = "Page1";
                public readonly string Page2 = "Page2";
                public readonly string QuickLinks = "QuickLinks";
                public readonly string QuickLinksV2 = "QuickLinksV2";
                public readonly string Registration = "Registration";
                public readonly string RegistrationV2 = "RegistrationV2";
            }
            public readonly string DashBoard = "~/Views/Home/DashBoard.cshtml";
            public readonly string Datatable = "~/Views/Home/Datatable.cshtml";
            public readonly string Index = "~/Views/Home/Index.cshtml";
            public readonly string Login = "~/Views/Home/Login.cshtml";
            public readonly string Page1 = "~/Views/Home/Page1.cshtml";
            public readonly string Page2 = "~/Views/Home/Page2.cshtml";
            public readonly string QuickLinks = "~/Views/Home/QuickLinks.cshtml";
            public readonly string QuickLinksV2 = "~/Views/Home/QuickLinksV2.cshtml";
            public readonly string Registration = "~/Views/Home/Registration.cshtml";
            public readonly string RegistrationV2 = "~/Views/Home/RegistrationV2.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_HomeController : PepinoHealth.App.Controllers.HomeController
    {
        public T4MVC_HomeController() : base(Dummy.Instance) { }

        [NonAction]
        partial void LoginOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Login()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Login);
            LoginOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void QuickLinksV2Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult QuickLinksV2()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QuickLinksV2);
            QuickLinksV2Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RegistrationV2Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult RegistrationV2()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RegistrationV2);
            RegistrationV2Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RevisitRegistrationOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult RevisitRegistration()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RevisitRegistration);
            RevisitRegistrationOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void LogOutOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string returnUrl);

        [NonAction]
        public override System.Web.Mvc.ActionResult LogOut(string returnUrl)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LogOut);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "returnUrl", returnUrl);
            LogOutOverride(callInfo, returnUrl);
            return callInfo;
        }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DashBoardOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult DashBoard()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DashBoard);
            DashBoardOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void QuickLinksOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult QuickLinks()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QuickLinks);
            QuickLinksOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RegistrationOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Registration()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Registration);
            RegistrationOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Page1Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Page1()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Page1);
            Page1Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Page2Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Page2()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Page2);
            Page2Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DatatableOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Datatable()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Datatable);
            DatatableOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AdvanceReceiptOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult AdvanceReceipt()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AdvanceReceipt);
            AdvanceReceiptOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ValidateUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PepinoHealth.CL.User.Profile profile);

        [NonAction]
        public override System.Web.Mvc.ActionResult ValidateUser(PepinoHealth.CL.User.Profile profile)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ValidateUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "profile", profile);
            ValidateUserOverride(callInfo, profile);
            return callInfo;
        }

        [NonAction]
        partial void GrantAccessOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PepinoHealth.CL.User.Profile profile);

        [NonAction]
        public override System.Web.Mvc.ActionResult GrantAccess(PepinoHealth.CL.User.Profile profile)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GrantAccess);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "profile", profile);
            GrantAccessOverride(callInfo, profile);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
