// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace PepinoHealth.App.Controllers
{
    public partial class OutPatientController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public OutPatientController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected OutPatientController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CRUDOPRegistrationDetails()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CRUDOPRegistrationDetails);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ManagePatientDetails()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ManagePatientDetails);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DownloadFile()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownloadFile);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeletePatientFile()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeletePatientFile);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SearchOPDetailsByUHID()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SearchOPDetailsByUHID);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetOPDetailsByUHID()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetOPDetailsByUHID);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public OutPatientController Actions { get { return MVC.OutPatient; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "OutPatient";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "OutPatient";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string OPRegistration = "OPRegistration";
            public readonly string OPRevisitRegistration = "OPRevisitRegistration";
            public readonly string DoctorDesk = "DoctorDesk";
            public readonly string OutPatientReports = "OutPatientReports";
            public readonly string NextVisitDetails = "NextVisitDetails";
            public readonly string PatientTreatment = "PatientTreatment";
            public readonly string GetMaxOutPatientId = "GetMaxOutPatientId";
            public readonly string GenerateBarcode = "GenerateBarcode";
            public readonly string GetOutPatientDepartmentDetails = "GetOutPatientDepartmentDetails";
            public readonly string CRUDOPRegistrationDetails = "CRUDOPRegistrationDetails";
            public readonly string GetPatientDetails = "GetPatientDetails";
            public readonly string ManagePatientDetails = "ManagePatientDetails";
            public readonly string DownloadFile = "DownloadFile";
            public readonly string DeletePatientFile = "DeletePatientFile";
            public readonly string SearchOPDetailsByUHID = "SearchOPDetailsByUHID";
            public readonly string GetOPDetailsByUHID = "GetOPDetailsByUHID";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string OPRegistration = "OPRegistration";
            public const string OPRevisitRegistration = "OPRevisitRegistration";
            public const string DoctorDesk = "DoctorDesk";
            public const string OutPatientReports = "OutPatientReports";
            public const string NextVisitDetails = "NextVisitDetails";
            public const string PatientTreatment = "PatientTreatment";
            public const string GetMaxOutPatientId = "GetMaxOutPatientId";
            public const string GenerateBarcode = "GenerateBarcode";
            public const string GetOutPatientDepartmentDetails = "GetOutPatientDepartmentDetails";
            public const string CRUDOPRegistrationDetails = "CRUDOPRegistrationDetails";
            public const string GetPatientDetails = "GetPatientDetails";
            public const string ManagePatientDetails = "ManagePatientDetails";
            public const string DownloadFile = "DownloadFile";
            public const string DeletePatientFile = "DeletePatientFile";
            public const string SearchOPDetailsByUHID = "SearchOPDetailsByUHID";
            public const string GetOPDetailsByUHID = "GetOPDetailsByUHID";
        }


        static readonly ActionParamsClass_CRUDOPRegistrationDetails s_params_CRUDOPRegistrationDetails = new ActionParamsClass_CRUDOPRegistrationDetails();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CRUDOPRegistrationDetails CRUDOPRegistrationDetailsParams { get { return s_params_CRUDOPRegistrationDetails; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CRUDOPRegistrationDetails
        {
            public readonly string outPatientRegistration = "outPatientRegistration";
        }
        static readonly ActionParamsClass_ManagePatientDetails s_params_ManagePatientDetails = new ActionParamsClass_ManagePatientDetails();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ManagePatientDetails ManagePatientDetailsParams { get { return s_params_ManagePatientDetails; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ManagePatientDetails
        {
            public readonly string name = "name";
        }
        static readonly ActionParamsClass_DownloadFile s_params_DownloadFile = new ActionParamsClass_DownloadFile();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DownloadFile DownloadFileParams { get { return s_params_DownloadFile; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DownloadFile
        {
            public readonly string fileName = "fileName";
        }
        static readonly ActionParamsClass_DeletePatientFile s_params_DeletePatientFile = new ActionParamsClass_DeletePatientFile();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeletePatientFile DeletePatientFileParams { get { return s_params_DeletePatientFile; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeletePatientFile
        {
            public readonly string fileName = "fileName";
        }
        static readonly ActionParamsClass_SearchOPDetailsByUHID s_params_SearchOPDetailsByUHID = new ActionParamsClass_SearchOPDetailsByUHID();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SearchOPDetailsByUHID SearchOPDetailsByUHIDParams { get { return s_params_SearchOPDetailsByUHID; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SearchOPDetailsByUHID
        {
            public readonly string StartDate = "StartDate";
            public readonly string EndDate = "EndDate";
        }
        static readonly ActionParamsClass_GetOPDetailsByUHID s_params_GetOPDetailsByUHID = new ActionParamsClass_GetOPDetailsByUHID();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetOPDetailsByUHID GetOPDetailsByUHIDParams { get { return s_params_GetOPDetailsByUHID; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetOPDetailsByUHID
        {
            public readonly string UHID = "UHID";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string DoctorDesk = "DoctorDesk";
                public readonly string NextVisitDetails = "NextVisitDetails";
                public readonly string OPRegistration = "OPRegistration";
                public readonly string OPRevisitRegistration = "OPRevisitRegistration";
                public readonly string OutPatientReports = "OutPatientReports";
                public readonly string PatientTreatment = "PatientTreatment";
            }
            public readonly string DoctorDesk = "~/Views/OutPatient/DoctorDesk.cshtml";
            public readonly string NextVisitDetails = "~/Views/OutPatient/NextVisitDetails.cshtml";
            public readonly string OPRegistration = "~/Views/OutPatient/OPRegistration.cshtml";
            public readonly string OPRevisitRegistration = "~/Views/OutPatient/OPRevisitRegistration.cshtml";
            public readonly string OutPatientReports = "~/Views/OutPatient/OutPatientReports.cshtml";
            public readonly string PatientTreatment = "~/Views/OutPatient/PatientTreatment.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_OutPatientController : PepinoHealth.App.Controllers.OutPatientController
    {
        public T4MVC_OutPatientController() : base(Dummy.Instance) { }

        [NonAction]
        partial void OPRegistrationOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult OPRegistration()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.OPRegistration);
            OPRegistrationOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void OPRevisitRegistrationOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult OPRevisitRegistration()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.OPRevisitRegistration);
            OPRevisitRegistrationOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DoctorDeskOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult DoctorDesk()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DoctorDesk);
            DoctorDeskOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void OutPatientReportsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult OutPatientReports()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.OutPatientReports);
            OutPatientReportsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void NextVisitDetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult NextVisitDetails()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NextVisitDetails);
            NextVisitDetailsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PatientTreatmentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult PatientTreatment()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PatientTreatment);
            PatientTreatmentOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetMaxOutPatientIdOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetMaxOutPatientId()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetMaxOutPatientId);
            GetMaxOutPatientIdOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GenerateBarcodeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GenerateBarcode()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GenerateBarcode);
            GenerateBarcodeOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetOutPatientDepartmentDetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetOutPatientDepartmentDetails()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetOutPatientDepartmentDetails);
            GetOutPatientDepartmentDetailsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CRUDOPRegistrationDetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PepinoHealth.CL.OPModal.OutPatientModal.OutPatientRegistration outPatientRegistration);

        [NonAction]
        public override System.Web.Mvc.ActionResult CRUDOPRegistrationDetails(PepinoHealth.CL.OPModal.OutPatientModal.OutPatientRegistration outPatientRegistration)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CRUDOPRegistrationDetails);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "outPatientRegistration", outPatientRegistration);
            CRUDOPRegistrationDetailsOverride(callInfo, outPatientRegistration);
            return callInfo;
        }

        [NonAction]
        partial void GetPatientDetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetPatientDetails()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetPatientDetails);
            GetPatientDetailsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ManagePatientDetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string name);

        [NonAction]
        public override System.Web.Mvc.ActionResult ManagePatientDetails(string name)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ManagePatientDetails);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "name", name);
            ManagePatientDetailsOverride(callInfo, name);
            return callInfo;
        }

        [NonAction]
        partial void DownloadFileOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string fileName);

        [NonAction]
        public override System.Web.Mvc.ActionResult DownloadFile(string fileName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownloadFile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fileName", fileName);
            DownloadFileOverride(callInfo, fileName);
            return callInfo;
        }

        [NonAction]
        partial void DeletePatientFileOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string fileName);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeletePatientFile(string fileName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeletePatientFile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fileName", fileName);
            DeletePatientFileOverride(callInfo, fileName);
            return callInfo;
        }

        [NonAction]
        partial void SearchOPDetailsByUHIDOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.DateTime StartDate, System.DateTime EndDate);

        [NonAction]
        public override System.Web.Mvc.ActionResult SearchOPDetailsByUHID(System.DateTime StartDate, System.DateTime EndDate)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SearchOPDetailsByUHID);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "StartDate", StartDate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "EndDate", EndDate);
            SearchOPDetailsByUHIDOverride(callInfo, StartDate, EndDate);
            return callInfo;
        }

        [NonAction]
        partial void GetOPDetailsByUHIDOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string UHID);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetOPDetailsByUHID(string UHID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetOPDetailsByUHID);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "UHID", UHID);
            GetOPDetailsByUHIDOverride(callInfo, UHID);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
