// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC
{
    public static PepinoHealth.App.Controllers.HomeController Home = new PepinoHealth.App.Controllers.T4MVC_HomeController();
    public static PepinoHealth.App.Controllers.IPModuleController IPModule = new PepinoHealth.App.Controllers.T4MVC_IPModuleController();
    public static PepinoHealth.App.Controllers.OPBillingController OPBilling = new PepinoHealth.App.Controllers.T4MVC_OPBillingController();
    public static PepinoHealth.App.Controllers.OPIPReportsController OPIPReports = new PepinoHealth.App.Controllers.T4MVC_OPIPReportsController();
    public static PepinoHealth.App.Controllers.OutPatientController OutPatient = new PepinoHealth.App.Controllers.T4MVC_OutPatientController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
}

#pragma warning disable 0436
namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}
#pragma warning restore 0436

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Scripts {
        public const string UrlPath = "~/Scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class bootstrap {
            public const string UrlPath = "~/Scripts/bootstrap";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class bootstrap_validator {
                public const string UrlPath = "~/Scripts/bootstrap/bootstrap-validator";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string bootstrap_validator_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap-validator.min.js") ? Url("bootstrap-validator.min.js") : Url("bootstrap-validator.js");
                public static readonly string bootstrap_validator_min_js = Url("bootstrap-validator.min.js");
            }
        
            public static readonly string bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap.min.js") ? Url("bootstrap.min.js") : Url("bootstrap.js");
            public static readonly string bootstrap_min_js = Url("bootstrap.min.js");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class chart {
            public const string UrlPath = "~/Scripts/chart";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string chart_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/chart.min.js") ? Url("chart.min.js") : Url("chart.js");
            public static readonly string chart_min_js = Url("chart.min.js");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class dynamic {
            public const string UrlPath = "~/Scripts/dynamic";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string master_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/master.min.js") ? Url("master.min.js") : Url("master.js");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class jquery {
            public const string UrlPath = "~/Scripts/jquery";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string jquery_3_6_0_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery-3.6.0.min.js") ? Url("jquery-3.6.0.min.js") : Url("jquery-3.6.0.js");
            public static readonly string jquery_3_6_0_min_js = Url("jquery-3.6.0.min.js");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class jquery_validate {
                public const string UrlPath = "~/Scripts/jquery/jquery.validate";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string jquery_validate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.validate.min.js") ? Url("jquery.validate.min.js") : Url("jquery.validate.js");
                public static readonly string jquery_validate_min_js = Url("jquery.validate.min.js");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class jquery_validate_vsdoc {
                public const string UrlPath = "~/Scripts/jquery/jquery.validate-vsdoc";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string jquery_validate_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.validate-vsdoc.min.js") ? Url("jquery.validate-vsdoc.min.js") : Url("jquery.validate-vsdoc.js");
                public static readonly string jquery_validate_vsdoc_min_js = Url("jquery.validate-vsdoc.min.js");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class jquery_validate_unobtrusive {
                public const string UrlPath = "~/Scripts/jquery/jquery.validate.unobtrusive";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.validate.unobtrusive.min.js") ? Url("jquery.validate.unobtrusive.min.js") : Url("jquery.validate.unobtrusive.js");
                public static readonly string jquery_validate_unobtrusive_min_js = Url("jquery.validate.unobtrusive.min.js");
            }
        
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class linq {
            public const string UrlPath = "~/Scripts/linq";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string linq_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/linq.min.js") ? Url("linq.min.js") : Url("linq.js");
            public static readonly string linq_min_js = Url("linq.min.js");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class material {
            public const string UrlPath = "~/Scripts/material";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class material_datetimepicker {
                public const string UrlPath = "~/Scripts/material/material-datetimepicker";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string material_datetimepicker_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/material-datetimepicker.min.js") ? Url("material-datetimepicker.min.js") : Url("material-datetimepicker.js");
                public static readonly string material_datetimepicker_min_js = Url("material-datetimepicker.min.js");
            }
        
            public static readonly string material_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/material.min.js") ? Url("material.min.js") : Url("material.js");
            public static readonly string material_min_js = Url("material.min.js");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class modernizr {
            public const string UrlPath = "~/Scripts/modernizr";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string modernizr_2_8_3_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/modernizr-2.8.3.min.js") ? Url("modernizr-2.8.3.min.js") : Url("modernizr-2.8.3.js");
            public static readonly string modernizr_2_8_3_min_js = Url("modernizr-2.8.3.min.js");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class moment {
            public const string UrlPath = "~/Scripts/moment";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string moment_with_locales_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/moment-with-locales.min.js") ? Url("moment-with-locales.min.js") : Url("moment-with-locales.js");
            public static readonly string moment_with_locales_min_js = Url("moment-with-locales.min.js");
            public static readonly string moment_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/moment.min.js") ? Url("moment.min.js") : Url("moment.js");
            public static readonly string moment_min_js = Url("moment.min.js");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class popper {
            public const string UrlPath = "~/Scripts/popper";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class umd {
                public const string UrlPath = "~/Scripts/popper/umd";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string popper_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/popper.min.js") ? Url("popper.min.js") : Url("popper.js");
                public static readonly string popper_min_js = Url("popper.min.js");
            }
        
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class trumbowyg {
            public const string UrlPath = "~/Scripts/trumbowyg";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string es_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/es.min.js") ? Url("es.min.js") : Url("es.js");
            public static readonly string es_min_js = Url("es.min.js");
            public static readonly string trumbowyg_colors_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/trumbowyg.colors.min.js") ? Url("trumbowyg.colors.min.js") : Url("trumbowyg.colors.js");
            public static readonly string trumbowyg_colors_min_js = Url("trumbowyg.colors.min.js");
            public static readonly string trumbowyg_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/trumbowyg.min.js") ? Url("trumbowyg.min.js") : Url("trumbowyg.js");
            public static readonly string trumbowyg_min_js = Url("trumbowyg.min.js");
            public static readonly string trumbowyg_table_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/trumbowyg.table.min.js") ? Url("trumbowyg.table.min.js") : Url("trumbowyg.table.js");
            public static readonly string trumbowyg_table_min_js = Url("trumbowyg.table.min.js");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class views {
            public const string UrlPath = "~/Scripts/views";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class common {
                public const string UrlPath = "~/Scripts/views/common";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string common_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/common.min.js") ? Url("common.min.js") : Url("common.js");
                public static readonly string common_min_js = Url("common.min.js");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class opipviews {
                public const string UrlPath = "~/Scripts/views/opipviews";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string opipviews_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/opipviews.min.js") ? Url("opipviews.min.js") : Url("opipviews.js");
                public static readonly string opipviews_min_js = Url("opipviews.min.js");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class outpatient {
                public const string UrlPath = "~/Scripts/views/outpatient";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string outpatient_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/outpatient.min.js") ? Url("outpatient.min.js") : Url("outpatient.js");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class user {
                public const string UrlPath = "~/Scripts/views/user";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string register_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/register.min.js") ? Url("register.min.js") : Url("register.js");
                public static readonly string register_min_js = Url("register.min.js");
            }
        
        }
    
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Content {
        public const string UrlPath = "~/Content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class bootstrap {
            public const string UrlPath = "~/Content/bootstrap";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class bootstrap_validator {
                public const string UrlPath = "~/Content/bootstrap/bootstrap-validator";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string bootstrap_validator_less = Url("bootstrap-validator.less");
            }
        
            public static readonly string bootstrap_less = Url("bootstrap.less");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class common {
            public const string UrlPath = "~/Content/common";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string common_less = Url("common.less");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class dynamic {
            public const string UrlPath = "~/Content/dynamic";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string master_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/master.min.css") ? Url("master.min.css") : Url("master.css");
            public static readonly string master_less = Url("master.less");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class fonts {
            public const string UrlPath = "~/Content/fonts";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class google_hind_siliguri {
                public const string UrlPath = "~/Content/fonts/google-hind-siliguri";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string HindSiliguri_Bold_ttf = Url("HindSiliguri-Bold.ttf");
                public static readonly string HindSiliguri_Light_ttf = Url("HindSiliguri-Light.ttf");
                public static readonly string HindSiliguri_Medium_ttf = Url("HindSiliguri-Medium.ttf");
                public static readonly string HindSiliguri_Regular_ttf = Url("HindSiliguri-Regular.ttf");
                public static readonly string HindSiliguri_SemiBold_ttf = Url("HindSiliguri-SemiBold.ttf");
            }
        
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class images {
            public const string UrlPath = "~/Content/images";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class common {
                public const string UrlPath = "~/Content/images/common";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string loader_gif = Url("loader.gif");
                public static readonly string loader_svg = Url("loader.svg");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class header {
                public const string UrlPath = "~/Content/images/header";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string pepino_health_logo_png = Url("pepino-health-logo.png");
            }
        
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class material {
            public const string UrlPath = "~/Content/material";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class material_datetimepicker {
                public const string UrlPath = "~/Content/material/material-datetimepicker";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string material_datetimepicker_less = Url("material-datetimepicker.less");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class material_icons {
                public const string UrlPath = "~/Content/material/material-icons";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class icons {
                    public const string UrlPath = "~/Content/material/material-icons/icons";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                    public static readonly string MaterialIcons_Regular_eot = Url("MaterialIcons-Regular.eot");
                    public static readonly string MaterialIcons_Regular_ttf = Url("MaterialIcons-Regular.ttf");
                    public static readonly string MaterialIcons_Regular_woff = Url("MaterialIcons-Regular.woff");
                    public static readonly string MaterialIcons_Regular_woff2 = Url("MaterialIcons-Regular.woff2");
                }
            
                public static readonly string material_icons_less = Url("material-icons.less");
            }
        
            public static readonly string material_less = Url("material.less");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class notification {
            public const string UrlPath = "~/Content/notification";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string notification_less = Url("notification.less");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class site {
            public const string UrlPath = "~/Content/site";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string site_less = Url("site.less");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class trumbowyg {
            public const string UrlPath = "~/Content/trumbowyg";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string trumbowyg_colors_less = Url("trumbowyg.colors.less");
            public static readonly string trumbowyg_less = Url("trumbowyg.less");
        }
    
    }

    
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        public static partial class Scripts 
        {
            public static partial class bootstrap 
            {
                public static partial class bootstrap_validator 
                {
                    public static class Assets
                    {
                        public static readonly string bootstrap_validator_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/bootstrap/bootstrap-validator/bootstrap-validator.js"); 
                        public static readonly string bootstrap_validator_min_js_ = T4MVCHelpers.ProcessAssetPath("~/Scripts/bootstrap/bootstrap-validator/bootstrap-validator.min.js"); 
                    }
                }
                public static class Assets
                {
                    public static readonly string bootstrap_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/bootstrap/bootstrap.js"); 
                    public static readonly string bootstrap_min_js_ = T4MVCHelpers.ProcessAssetPath("~/Scripts/bootstrap/bootstrap.min.js"); 
                }
            }
            public static partial class chart 
            {
                public static class Assets
                {
                    public static readonly string chart_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/chart/chart.js"); 
                    public static readonly string chart_min_js_ = T4MVCHelpers.ProcessAssetPath("~/Scripts/chart/chart.min.js"); 
                }
            }
            public static partial class dynamic 
            {
                public static class Assets
                {
                    public static readonly string master_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/dynamic/master.js"); 
                }
            }
            public static partial class jquery 
            {
                public static partial class jquery_validate 
                {
                    public static class Assets
                    {
                        public static readonly string jquery_validate_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery/jquery.validate/jquery.validate.js"); 
                        public static readonly string jquery_validate_min_js_ = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery/jquery.validate/jquery.validate.min.js"); 
                    }
                }
                public static partial class jquery_validate_vsdoc 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class jquery_validate_unobtrusive 
                {
                    public static class Assets
                    {
                        public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery/jquery.validate.unobtrusive/jquery.validate.unobtrusive.js"); 
                        public static readonly string jquery_validate_unobtrusive_min_js_ = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery/jquery.validate.unobtrusive/jquery.validate.unobtrusive.min.js"); 
                    }
                }
                public static class Assets
                {
                    public static readonly string jquery_3_6_0_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery/jquery-3.6.0.js"); 
                    public static readonly string jquery_3_6_0_min_js_ = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery/jquery-3.6.0.min.js"); 
                }
            }
            public static partial class linq 
            {
                public static class Assets
                {
                    public static readonly string linq_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/linq/linq.js"); 
                    public static readonly string linq_min_js_ = T4MVCHelpers.ProcessAssetPath("~/Scripts/linq/linq.min.js"); 
                }
            }
            public static partial class material 
            {
                public static partial class material_datetimepicker 
                {
                    public static class Assets
                    {
                        public static readonly string material_datetimepicker_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/material/material-datetimepicker/material-datetimepicker.js"); 
                        public static readonly string material_datetimepicker_min_js_ = T4MVCHelpers.ProcessAssetPath("~/Scripts/material/material-datetimepicker/material-datetimepicker.min.js"); 
                    }
                }
                public static class Assets
                {
                    public static readonly string material_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/material/material.js"); 
                    public static readonly string material_min_js_ = T4MVCHelpers.ProcessAssetPath("~/Scripts/material/material.min.js"); 
                }
            }
            public static partial class modernizr 
            {
                public static class Assets
                {
                    public static readonly string modernizr_2_8_3_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/modernizr/modernizr-2.8.3.js"); 
                    public static readonly string modernizr_2_8_3_min_js_ = T4MVCHelpers.ProcessAssetPath("~/Scripts/modernizr/modernizr-2.8.3.min.js"); 
                }
            }
            public static partial class moment 
            {
                public static class Assets
                {
                    public static readonly string moment_with_locales_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/moment/moment-with-locales.js"); 
                    public static readonly string moment_with_locales_min_js_ = T4MVCHelpers.ProcessAssetPath("~/Scripts/moment/moment-with-locales.min.js"); 
                    public static readonly string moment_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/moment/moment.js"); 
                    public static readonly string moment_min_js_ = T4MVCHelpers.ProcessAssetPath("~/Scripts/moment/moment.min.js"); 
                }
            }
            public static partial class popper 
            {
                public static partial class umd 
                {
                    public static class Assets
                    {
                        public static readonly string popper_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/popper/umd/popper.js"); 
                        public static readonly string popper_min_js_ = T4MVCHelpers.ProcessAssetPath("~/Scripts/popper/umd/popper.min.js"); 
                    }
                }
                public static class Assets
                {
                }
            }
            public static partial class trumbowyg 
            {
                public static class Assets
                {
                    public static readonly string es_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/trumbowyg/es.js"); 
                    public static readonly string es_min_js_ = T4MVCHelpers.ProcessAssetPath("~/Scripts/trumbowyg/es.min.js"); 
                    public static readonly string trumbowyg_colors_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/trumbowyg/trumbowyg.colors.js"); 
                    public static readonly string trumbowyg_colors_min_js_ = T4MVCHelpers.ProcessAssetPath("~/Scripts/trumbowyg/trumbowyg.colors.min.js"); 
                    public static readonly string trumbowyg_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/trumbowyg/trumbowyg.js"); 
                    public static readonly string trumbowyg_min_js_ = T4MVCHelpers.ProcessAssetPath("~/Scripts/trumbowyg/trumbowyg.min.js"); 
                    public static readonly string trumbowyg_table_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/trumbowyg/trumbowyg.table.js"); 
                    public static readonly string trumbowyg_table_min_js_ = T4MVCHelpers.ProcessAssetPath("~/Scripts/trumbowyg/trumbowyg.table.min.js"); 
                }
            }
            public static partial class views 
            {
                public static partial class common 
                {
                    public static class Assets
                    {
                        public static readonly string common_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/views/common/common.js"); 
                        public static readonly string common_min_js_ = T4MVCHelpers.ProcessAssetPath("~/Scripts/views/common/common.min.js"); 
                    }
                }
                public static partial class opipviews 
                {
                    public static class Assets
                    {
                        public static readonly string opipviews_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/views/opipviews/opipviews.js"); 
                        public static readonly string opipviews_min_js_ = T4MVCHelpers.ProcessAssetPath("~/Scripts/views/opipviews/opipviews.min.js"); 
                    }
                }
                public static partial class outpatient 
                {
                    public static class Assets
                    {
                        public static readonly string outpatient_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/views/outpatient/outpatient.js"); 
                    }
                }
                public static partial class user 
                {
                    public static class Assets
                    {
                        public static readonly string register_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/views/user/register.js"); 
                        public static readonly string register_min_js_ = T4MVCHelpers.ProcessAssetPath("~/Scripts/views/user/register.min.js"); 
                    }
                }
                public static class Assets
                {
                }
            }
            public static class Assets
            {
            }
        }
        public static partial class Content 
        {
            public static partial class bootstrap 
            {
                public static partial class bootstrap_validator 
                {
                    public static class Assets
                    {
                    }
                }
                public static class Assets
                {
                }
            }
            public static partial class common 
            {
                public static class Assets
                {
                }
            }
            public static partial class dynamic 
            {
                public static class Assets
                {
                    public static readonly string master_css = T4MVCHelpers.ProcessAssetPath("~/Content/dynamic/master.css");
                }
            }
            public static partial class fonts 
            {
                public static partial class google_hind_siliguri 
                {
                    public static class Assets
                    {
                    }
                }
                public static class Assets
                {
                }
            }
            public static partial class images 
            {
                public static partial class common 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class header 
                {
                    public static class Assets
                    {
                    }
                }
                public static class Assets
                {
                }
            }
            public static partial class material 
            {
                public static partial class material_datetimepicker 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class material_icons 
                {
                    public static partial class icons 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static class Assets
                    {
                    }
                }
                public static class Assets
                {
                }
            }
            public static partial class notification 
            {
                public static class Assets
                {
                }
            }
            public static partial class site 
            {
                public static class Assets
                {
                }
            }
            public static partial class trumbowyg 
            {
                public static class Assets
                {
                }
            }
            public static class Assets
            {
            }
        }
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    private static string ProcessAssetPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and should retain this prefix
        return virtualPath;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;
    public static Func<string, string> ProcessAssetPath = ProcessAssetPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114


